# Generated by Django 5.0.6 on 2024-10-01 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0003_profile_bio_profile_image_alter_profile_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_voice_channel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='server',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='server_images/'),
        ),
        migrations.AddField(
            model_name='server',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='servers', to=settings.AUTH_USER_MODEL),
        ),
    ]
